### ISSUE TITLE
Issue with internal oceans in bathy file

### ISSUE THREAD

**Issue by tiphe-cerege** [CEREGE-CL/netcdf_editor_app#104]
Le calcul des mers internes avec le fichier bathymétrie semble poser un problème dans les zones de bordure (ie à 180 et -180 de longitude), cf Rupelian_Final_pax_YD_letteron.nc Last Modified on 2021-03-04 puis Internal Oceans, il en reste un et pourtant quand je regarde, cela n'en est pas un ? Merci d'avance !

**Comment by tiphe-cerege** [comment]
Ok, that's fine with me !

**Comment by WesleyTheGeolien** [comment]
Ok @tiphe-cerege This has been fixed  and deployed
