### ISSUE TITLE
curvilinear.nc seems uncorrect

### ISSUE THREAD

**Issue by PBrockmann** [CEREGE-CL/netcdf_editor_app#110]
I have made a small check on the curvilinear file proposed in the data directory and discovered with ferret that the curvilinear.nc file may have uncorrect longitude and latitude positions. See plot bellow.
![curv](https://user-images.githubusercontent.com/5402758/111332347-ff71b300-8671-11eb-99b9-60fb96625ef0.gif)

```
$ ferret
yes? use curvilinear.nc
yes? shade/modulo BATHYMETRY, NAV_LON, NAV_LAT
yes? go land red

```

**Comment by WesleyTheGeolien** [comment]
@PBrockmann I'm not a whiz on Paleo geographies here but the `go land red` is todays geography right? the curvilinear file is a paleo geography (can't remember the age of the top of my head) so this could be the reason why they aren't aligning?

**Comment by PBrockmann** [comment]
Indeed. Might be the reason. Could you check with the provider of the file ?

**Comment by WesleyTheGeolien** [comment]
Ok so the file is an ORCA file based on the paleo geography 38Ma ago which should explain the mismatch
