### ISSUE TITLE
Download files 

### ISSUE THREAD

**Issue by AntaCl** [CEREGE-CL/netcdf_editor_app#125]
Looks like the download function crashed : 

![Capture d’écran 2021-04-16 à 10 26 21](https://user-images.githubusercontent.com/73880121/114995742-6e733f00-9e9e-11eb-9b37-ac79141ea51b.png)

when clicking on the download button.

**Comment by WesleyTheGeolien** [comment]
Ok so this is due to the fact the we are parsing filenames like this `"_".join(filename.split("."))` which is changing the last one as well eg. the `.nc`
