### ISSUE TITLE
Provide all info for the initial PaleoDEM and more

### ISSUE THREAD

**Issue by tiphe-cerege** [CEREGE-CL/netcdf_editor_app#134]
In order to have a good traceability of who did what and on a very valuable suggestion of Anta Sarr, we should add 

1. When uploading the initial paleDEM, request from the user to state clearly the authors of the paleogeography, paleomag or hotspot reference framework, some may also think to add main hypothesis did on, in particular, configuration of marine gateways and of main orogens
2. After modifications of the paleoDEMS for ORCA2 grid purpose, clearly state the choices that have been done (closed or enlarged gateways) for the paleobathy file. Same should hold for pfts spatial distrib of ORCHIDEE. 
3. Also add which config of PALEORCA grid has been used (in particular where are located the northern hemisphere singular points)

**Comment by WesleyTheGeolien** [comment]
@tiphe-cerege @AntaCl could you please confirm the points below

> 1. When uploading the initial paleDEM, request from the user to state clearly the authors of the paleogeography, paleomag or hotspot reference framework, some may also think to add main hypothesis did on, in particular, configuration of marine gateways and of main orogens

For this we do this when first uploading the file? And add :
- Author / reference (required)
- Hypothesis (not required)
- Age???

> 2. After modifications of the paleoDEMS for ORCA2 grid purpose, clearly state the choices that have been done (closed or enlarged gateways) for the paleobathy file. Same should hold for pfts spatial distrib of ORCHIDEE.

On internal oceans, passage problems (sub basins ??, complex viewer ??), we should add a pop up to enter the info? → Just a text entry?

> 3. Also add which config of PALEORCA grid has been used (in particular where are located the northern hemisphere singular points)

Not sure How this is going to work? Where would we do this? in the "routing" stage?
