### ISSUE TITLE
Add some clarifications

### ISSUE THREAD

**Issue by tiphe-cerege** [CEREGE-CL/netcdf_editor_app#144]
When modifying the initial map at the internal oceans step, it should be nice to recall to the user that polar latitudes have to be carfeully handled keeping in mind two things, first, with ORCA2 grid, no ocean points are allowed poleward of 78°S and second, at the north pole, we should have only ocean or only land for the point poleward of 86°N (for the LMDz model)

**Comment by WesleyTheGeolien** [comment]
@tiphe-cerege doesn't this depend on the paleoorca grid that is going to be used in the routing stage?
