### ISSUE TITLE
Tant que j'y pense

### ISSUE THREAD

**Issue by tiphe-cerege** [CEREGE-CL/netcdf_editor_app#150]
1/Si tu charges une première fois le fichier, on tombe sur un message d'erreur, et il faut revenir en arriere pour que cela marche

2/ si tu modifies internal juste les valeurs de topo, cela relance bien routing mais cela met aussi passage problems et subbasins en rouge + relance l'étape MOSAIC

**Comment by WesleyTheGeolien** [comment]
The first point looks like some security built into Chrome that isn't in Safari ... I am trying to catch the None and we will redirect.

The second point has been dealt with normally there was a bug here.
