### ISSUE TITLE
Add Grid lines to help identified grid points

### ISSUE THREAD

**Issue by tiphe-cerege** [CEREGE-CL/netcdf_editor_app#20]

**Comment by WesleyTheGeolien** [comment]
@tiphe-cerege to resolve this and land initial works on grids I propose that the grid is always visible faintly see screenshots.

If this is a problem I suggest we open another issue to add on/off functionality to the grids.

Also the grid is currently only displayed the principal map. We could also show this on the other maps if necessary

![image](https://user-images.githubusercontent.com/18068320/97588823-2a2dd880-19fd-11eb-94ee-aca9fe783b94.png)
![image (1)](https://user-images.githubusercontent.com/18068320/97588821-2a2dd880-19fd-11eb-85bf-5e91356761c4.png)
![image (2)](https://user-images.githubusercontent.com/18068320/97588814-29954200-19fd-11eb-9678-7fffba964e50.png)
