### ISSUE TITLE
Use of a slider min/max to display colormap range

### ISSUE THREAD

**Issue by PBrockmann** [CEREGE-CL/netcdf_editor_app#32]

**Comment by PBrockmann** [comment]
See https://github.com/PBrockmann/threejsMap

**Comment by WesleyTheGeolien** [comment]
@PBrockmann I think this could be a useful change but just wondering about the trade-off between precision and facility? I wonder if linked widgets still allowing manual input as well as the range slider would be more effective? 

For example say someone wants a discrete colormap going from 0 -> 1000 with steps every 100 this, I presume, is easy by setting manual values? 

Whereas the use case of quickly being able to move the slide around as per your demo is easier with a range slider.

Something like this:
![image](https://user-images.githubusercontent.com/18068320/98231547-d66f4200-1f5c-11eb-99d9-a77bb3de5ef2.png)

**Comment by PBrockmann** [comment]
Indeed not sure that such a widget is available from Holoviews.  Is it ?
Users are usually confortable with  ferret specifications levels such as a triplet: min,max,delta 
And this simple input could be proposed as default in the interface. 
A range sliderswould be easier to use but does not cover the delta parameter indeed.

**Comment by WesleyTheGeolien** [comment]
@PBrockmann you can link widgets to get multiple widgets to show/edit the same value. I'll put a build together to see what you think.

@tiphe-cerege Talked to me about the _min, max, delta_ I think thi could be a great addition as well

**Comment by WesleyTheGeolien** [comment]
Here is a small demo of the functionality on the branch range-slider let me know what you think.

It would seem there is a lag when moving the range slider too quickly but this seems to be a holoviz problem rather than something I can change easily.

![Peek 2020-11-05 16-14](https://user-images.githubusercontent.com/18068320/98259172-0f6ddd80-1f82-11eb-93d1-5bc401a0e6ad.gif)
