### ISSUE TITLE
Change color palette and scale for easier viewing

### ISSUE THREAD

**Issue by jbladant** [CEREGE-CL/netcdf_editor_app#4]

**Comment by WesleyTheGeolien** [comment]
@jbladant could you be more specific with what you mean by change scale?

**Comment by WesleyTheGeolien** [comment]
@jbladant is their particular colormaps you are interested in, by default there are over 120 availible see here: https://holoviews.org/user_guide/Colormaps.html

**Comment by jbladant** [comment]
Colormaps:
Can you add all of them? With like a scrolling button for selection?

Scale:
I mean that when you zoom over a region, the scale on the right of the figure does not update. What could be nice would be that the scale adapt itself to reflect the maximum and the minimum values of the displayed cells.
For instance, if I zoom over a region in which the topography is between 200 m and 400 m, it could be nice that the scale update to display min value of 200 m and max value of 400 m rather than the default 0 - 2500 m value.

**Comment by WesleyTheGeolien** [comment]
Ok we'll start off with adding all the colormaps that is relatively "trival" work as for updating the scale on zoom that could be more complex!
