### ISSUE TITLE
Export Script

### ISSUE THREAD

**Issue by WesleyTheGeolien** [CEREGE-CL/netcdf_editor_app#47]
It would be useful to be able to eport the steps carried out on the file in a reproducible manner to be able to apply the same steps to a different file.

Suggested by @jbusecke.

Each calculation is stored in the `_undo_list` which mean theoretically we can export the undo list and this should give us access to all the steps needed to transform an initial dataset into the new dataset.

**Comment by jbusecke** [comment]
Thanks for remembering this @WesleyTheGeolien. This looks like a very cool project! Very excited to see where you are taking it!

**Comment by WesleyTheGeolien** [comment]
@jbusecke I have added the functionality to download a python file that accepts (and needs) an input file and attribute value from the command line.

The file will load the file apply the steps then write the file out.

One extra thing I was thinking of but not sure how useful it is, is that the coordinates names may change this means that the selection expressions will no longer work.

A work around would be to modify the selection expressions at runtime from command line arguments but I think this may complicate things, I am also wondering about coordinate systems in this case? What do you think?

**Comment by jbusecke** [comment]
Awesome, thanks a lot. I did not have time to give this a go, but will this week. 

> One extra thing I was thinking of but not sure how useful it is, is that the coordinates names may change this means that the selection expressions will no longer work.

Seems like a special case, which would require some manipulation of the data to occur? Perhaps in that case it is best that this does not work out of the box to avoid 'reproducing' results from the wrong (e.g. already manipulated) dataset? Or am I missing your point here?

**Comment by WesleyTheGeolien** [comment]
Nope I think you got my point @jbusecke I guess if anyone wanted to carry out the same manipulation on different data they could always do they mapping manually (ie. open up the script and do a search + replace)
