### ISSUE TITLE
Internal sea detection on paleo-orca files

### ISSUE THREAD

**Issue by AntaCl** [CEREGE-CL/netcdf_editor_app#55]
Internal seas detection does not work on paleo-orca files because bathymetry value are positive and routine is based on values below 0.  Attached file is an example, zoom over Japan and Ouest Pacific. Routine do not detect the Japan sea.

I think (but have to check) that internal seas detection is especially useful on paleo-orca files so would be good to be able either to set up internal seas for value above 0 or (in the case it is also useful for normal files, with negative bathymetry value) to be able to flip paleo-orca grid so internal seas are detected correctly (but final export should still be with positive value).

![InternalSea](https://user-images.githubusercontent.com/73880121/100075622-7aebf200-2e40-11eb-9708-9746791d0366.png)

**Comment by WesleyTheGeolien** [comment]
@AntaCl one quick thought could you select all the grid using the select tool and then do a percentage change of -200% (I think this should be the right amount to flip the values).

I agree though that maybe having a checkbox saying flip value would be more useful.

**Comment by AntaCl** [comment]
Tried to do it : il flips the grid (so I have bathymetry in negative values), but nothing displayed in the internal sea and diffusive passage boxes 
![Capture d’écran 2020-11-24 à 15 27 09](https://user-images.githubusercontent.com/73880121/100107056-8acbfc00-2e69-11eb-935d-ebbbd1feed3f.png)

**Comment by WesleyTheGeolien** [comment]
Ok again not ideal but feasible!

By transforming by -200% gives us the negative values, the oceans are then found with <= 0 meaning values of 0 are considered Ocean! (maybe we should make this < 0??) so by adding the transform Relatif: +0.0001 to everywhere internal oceans will appear.

![image](https://user-images.githubusercontent.com/18068320/100116186-b9e76b00-2e73-11eb-9988-087da6c346f6.png)

**Comment by WesleyTheGeolien** [comment]
This is fixed with #105
