### ISSUE TITLE
Generalize the use to variables other than topo/bathy ? 

### ISSUE THREAD

**Issue by psepulchre** [CEREGE-CL/netcdf_editor_app#92]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to use the app for variables other than topo/bathy.
For example PFT (plant functional types), that are 4-D variables (x,y,time,PFT-type).

**Describe the solution you'd like**
In the menu on the left, the user can access any variable, and decide for what dimension he/she can plot and modify the variable. 
**Describe alternatives you've considered**
Using the classic combo of python routines and nco commands to handle this.
**Additional context**

**Comment by WesleyTheGeolien** [comment]
Thanks for the idea @psepulchre! 

I can see how this could sort of work with see image below: 

- 1 dropdown to choose the X coords (from netcdf coordinates)
- 1 dropdown to choose the Y coords (from netcdf coordinates)
- 1 dropdown to choose the 3D coords (from netcdf coordinates)? this is where it starts to get complicated as it would work fine for tilmestep coords but not sure how generalised this could be?
- 1 range slider to choose which 3D to visualise

![Screenshot 2021-01-28 at 09 00 59](https://user-images.githubusercontent.com/18068320/106107862-bf00b900-6147-11eb-8fa4-ce93b180722e.png)

**Comment by psepulchre** [comment]
My feeling is you don't need to choose X and Y, but  only need control on other dimensions through range sliders.
So to I would suggest 

- a dropdown to choose the variable
- a slider to choose the timestep
- a slider to choose the additional dimension step

**Comment by WesleyTheGeolien** [comment]
Something along these lines: https://cerege-cl.github.io/Notebooks-Gallery/notebooks/Variable%20Explorer.html

![Screenshot 2021-01-28 at 10 45 52](https://user-images.githubusercontent.com/18068320/106119901-03935100-6156-11eb-99fe-f78263740ed7.png)

**Comment by WesleyTheGeolien** [comment]
@psepulchre if you know of anyone interested we could maybe use this example as a demo workflow for creating simple web apps?

**Comment by WesleyTheGeolien** [comment]
@psepulchre With the latest refactoring you can now gain access to the value changer for all files that have been uploaded it needs to be tested but this should be working with #105
